name: Build and Deploy train-ticket-reservation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # ------------------------------
  # 1️⃣ BUILD JOB
  # ------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔨 Build with Maven
        run: mvn clean package -DskipTests

      - name: 🗂 Find WAR file
        run: echo "WAR_FILE=$(ls target/*.war | head -n 1)" >> $GITHUB_ENV

      - name: ⬆️ Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: ${{ env.WAR_FILE }}

  # ------------------------------
  # 2️⃣ DEPLOY TO DEV
  # ------------------------------
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: 🚀 Deploy to DEV
        env:
          URL: http://35.167.3.28:8080/manager/text
          USER: ${{ secrets.TOMCAT_USER_DEV }}
          PASS: ${{ secrets.TOMCAT_PASS_DEV }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to DEV ($URL)"
          echo "Checking Tomcat connection..."
          curl -v -u "$USER:$PASS" "$URL/list" || exit 1

          echo "Deploying to Tomcat..."
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

  # ------------------------------
  # 3️⃣ DEPLOY TO TEST
  # ------------------------------
  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: 🚀 Deploy to TEST
        env:
          URL: http://35.167.3.29:8080/manager/text
          USER: ${{ secrets.TOMCAT_USER_TEST }}
          PASS: ${{ secrets.TOMCAT_PASS_TEST }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to TEST ($URL)"
          curl -v -u "$USER:$PASS" "$URL/list" || exit 1
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

  # ------------------------------
  # 4️⃣ DEPLOY TO PREPROD
  # ------------------------------
  deploy-preprod:
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: 🚀 Deploy to PREPROD
        env:
          URL: http://35.167.3.30:8080/manager/text
          USER: ${{ secrets.TOMCAT_USER_PREPROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PREPROD }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to PREPROD ($URL)"
          curl -v -u "$USER:$PASS" "$URL/list" || exit 1
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"

  # ------------------------------
  # 5️⃣ DEPLOY TO PROD
  # ------------------------------
  deploy-prod:
    needs: deploy-preprod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file

      - name: 🚀 Deploy to PROD
        env:
          URL: http://35.167.3.31:8080/manager/text
          USER: ${{ secrets.TOMCAT_USER_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PROD }}
        run: |
          WAR_FILE=$(ls *.war | head -n 1)
          echo "Deploying $WAR_FILE to PROD ($URL)"
          curl -v -u "$USER:$PASS" "$URL/list" || exit 1
          curl -v -u "$USER:$PASS" --fail --show-error -T "$WAR_FILE" \
            "$URL/deploy?path=/train-ticket-reservation&update=true"
